### ISSUE TITLE
Align with current WDI Fundamentals

### ISSUE THREAD

**Issue by austinc203** [ga-wdi-boston/fundamentals-diagnostic#102]
Questions should match existing fundamentals

**Comment by RealWeeks** [comment]
Link here http://fundamentals.generalassemb.ly/v3.0/09_chapter/05_lesson.html

This actually appears to be up to date with the current version because we focus on the second half of fundamentals (JS).

**Comment by RealWeeks** [comment]
@gaand  I believe this is not an issue. Either fundamentals was only stylistically updated only or someone updated this after the fundamentals update. This appears to be up to date.

**Comment by gaand** [comment]
Seems fine.
