### ISSUE TITLE
Images out of date

### ISSUE THREAD

**Issue by bernardlee** [ga-wdi-boston/fundamentals-diagnostic#145]
The images in the "Clone the repository" section are outdated.  I took some updated ones.

<img width="361" alt="screen shot 2017-01-09 at 11 07 27 am" src="https://cloud.githubusercontent.com/assets/12991284/21773348/ae228e80-d65c-11e6-95a0-1322f35aa0a4.png">

![screen shot 2017-01-09 at 11 07 35 am](https://cloud.githubusercontent.com/assets/12991284/21773361/b1123a6e-d65c-11e6-9f55-5011cbd10e07.png)

**Comment by payne-chris-r** [comment]
<img width="386" alt="screen shot 2017-03-16 at 4 03 51 pm" src="https://cloud.githubusercontent.com/assets/12667121/24016416/659baff4-0a62-11e7-85ee-5118f1a2c4fc.png">
