### ISSUE TITLE
Edit screenshot to use SSH url

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/fundamentals-diagnostic#23]
@gaand Not sure if you wanted this filed, but I remember you mentioned it this morning.

https://camo.githubusercontent.com/af653200d6d39d06d3f5debbdf829b184cd3e2c5/68747470733a2f2f68656c702e6769746875622e636f6d2f6173736574732f696d616765732f68656c702f7265706f7369746f72792f72656d6f7465732d75726c2e706e67

See https://github.com/ga-wdi-boston/fundamentals-diagnostic/commit/577dd049c417ba27ece0b8456ad4bc1be852ebeb#diff-04c6e90faac2675aa89e2176d2eec7d8R47

**Comment by RealWeeks** [comment]
@jrhorn424 @gaand updated with latest commit

**Comment by gaand** [comment]
"Copy to clipboard" still shows https.  I think it should also change.

**Comment by berziiii** [comment]
![image](https://cloud.githubusercontent.com/assets/8379295/15277267/c00d03b0-1acc-11e6-97bb-70e52ffdfd44.png)

Will this do?

**Comment by berziiii** [comment]
See commit ad3a962. Closing this issue. Reopen is needed. Thanks!
