### ISSUE TITLE
Remove $ from command prompt code blocks

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/fundamentals-diagnostic#27]
Developers usually copy and paste these blocks and `$` is a special character in prompts.

**Comment by RealWeeks** [comment]
@jrhorn424 remove in latest commit

**Comment by berziiii** [comment]
@J-Weeks, is this issue closed then? 

same with #24 and #23?

**Comment by berziiii** [comment]
@jrhorn424, due to above comments, can we close this issue? Thanks.
