### ISSUE TITLE
Archive WDI Prework Assessment

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/fundamentals-diagnostic#3]
https://github.com/ga-wdi-boston/wdi_1_ruby_assessment_prework

**Comment by berziiii** [comment]
@gaand, do you know if this repo was archived? Is so, can we close this issue? Thanks.

**Comment by jrhorn424** [comment]
It isn't archived. If the link still works, or if it works and doesn't redirect to ga-wdi-boston-attic, it isn't archived.

**Comment by gaand** [comment]
It is now archived.
